scorecard:
  version: v1alpha2
  output: text
  bundle: deploy/olm-catalog/reportportal-operator/0.0.1/metadata
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/rp5.reportportal.io_v1_reportportal_cr.yaml"
        csv-path: "deploy/olm-catalog/reportportal-operator/0.0.1/reportportal-operator.clusterserviceversion.yaml"
    - olm:
        cr-manifest:
          - "deploy/crds/rp5.reportportal.io_v1_reportportal_cr.yaml"
        csv-path: "deploy/olm-catalog/reportportal-operator/0.0.1/reportportal-operator.clusterserviceversion.yaml"
