# permissions for end users to view reportportals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reportportal-viewer-role
rules:
- apiGroups:
  - rp5.reportportal.io
  resources:
  - reportportals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rp5.reportportal.io
  resources:
  - reportportals/status
  verbs:
  - get
