# permissions for end users to edit serviceapiservicemonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceapiservicemonitor-editor-role
rules:
- apiGroups:
  - rp5.reportportal.io
  resources:
  - serviceapiservicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rp5.reportportal.io
  resources:
  - serviceapiservicemonitors/status
  verbs:
  - get
