# permissions for end users to view serviceapiservicemonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceapiservicemonitor-viewer-role
rules:
- apiGroups:
  - rp5.reportportal.io
  resources:
  - serviceapiservicemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rp5.reportportal.io
  resources:
  - serviceapiservicemonitors/status
  verbs:
  - get
