---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: reportportal-operator
  template:
    metadata:
      labels:
        name: reportportal-operator
    spec:
      serviceAccountName: reportportal-operator
      containers:
        - name: reportportal-operator
          # Replace this with the built image name
          image: "quay.io/waynesun09/rp5-operator:v0.0.5"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "reportportal-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
      volumes:
        - name: runner
          emptyDir: {}
