apiVersion: rp5.reportportal.io/v1
kind: ReportPortal
metadata:
  name: reportportal-sample
spec:
  # You cluster default router hostname
  app_domain: apps.test-example.com
  ui_replicas: 1
  api_replicas: 1
  index_image: quay.io/waynesun09/service-index:5.0.10
  uat_image: quay.io/waynesun09/service-authorization:5.3.5
  ui_image: quay.io/waynesun09/service-ui:5.3.5
  api_image: quay.io/waynesun09/service-api:5.3.5-rootless
  migration_image: quay.io/waynesun09/migrations:5.3.5
  analyzer_image: quay.io/waynesun09/service-auto-analyzer:5.3.5
  index_replicas: 1
  gateway_replicas: 1
  enable_pg_restic_backup: 'yes'
  pg_restic_s3_bucket_init: 'yes'
  pg_s3_bucket_name: pgbackup-123123
  pg_restic_password: rp_user
  es_s3_backup_dir: s3_backup
  es_snapshot_bucket: es-snapshot-123123
  es_backup_schedule: '@daily'
  s3_enabled: false
  accesskey: AKIAIOSFODNN7EXAMPLE
  secretkey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  s3_endpoint:
  default_bucket_name:
  bucket_prefix:
  integration_salt_path:
