- name: Update ReportPortal Operand status
  operator_sdk.util.k8s_status:
    api_version: rp5.reportportal.io/v1
    kind: ReportPortal
    name: "{{ rp_cr[0].metadata.name }}"
    namespace: "{{ meta.namespace }}"
    force: true
    status:
      conditions:
        - type: "Paused"
          status: "True"
          reason: "Successful"
          message: "Deployment is paused by ReportPortalRestore"
          LastTransitionTime: "{{ ansible_date_time.iso8601 }}"
  when: rp_cr[0].metadata.name is defined

- name: Fetch all RP deployments
  set_fact:
    rp_deployments: "{{ query('k8s', kind='Deployment', namespace=meta.namespace, label_selector='app=reportportal') }}"

- name: Scale down RP deployment
  include: scale_down_rp.yml

- name: Recover postgresql data
  include: pg_data_recovery.yml
  when:
    - pg_recovery | bool

- name: Restore elasticsearch data
  include: es_data_restore.yml
  when:
    - es_restore | bool

- name: Scale up RP deployment
  include: scale_up_rp.yml

- name: Set the operator status message
  set_fact:
    op_message: "{% if (pg_recovery | bool) and (es_restore | bool) %}Postgres WAL recovery and Elasticsearch snapshot restore have finished{% elif pg_recovery | bool %}Postgres WAL recovery have finished{% elif es_restore | bool %}Elasticsearch snapshot restore have finished{% else %}Nothing have been restored{% endif %}"

- name: Update ReportPortal Operand status back
  operator_sdk.util.k8s_status:
    api_version: rp5.reportportal.io/v1
    kind: ReportPortal
    name: "{{ rp_cr[0].metadata.name }}"
    namespace: "{{ meta.namespace }}"
    force: true
    status:
      conditions:
        - type: "Running"
          status: "True"
          reason: "Successful"
          message: "Updated status back to running"
          LastTransitionTime: "{{ ansible_date_time.iso8601 }}"
  when: rp_cr[0].metadata.name is defined

- name: Update ReportPortalRestore Operand status
  operator_sdk.util.k8s_status:
    api_version: rp5.reportportal.io/v1
    kind: ReportPortalRestore
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    status:
      conditions:
        - type: "Finished"
          status: "True"
          reason: "Successful"
          message: "{{ op_message }}"
          LastTransitionTime: "{{ ansible_date_time.iso8601 }}"
