- name: Deploy minio service
  include: deploy_minio.yml
  when: deploy_minio | bool

- name: Deploy postgresql service
  include: deploy_pg.yml
  when: deploy_postgresql | bool

- name: Deploy rabbitmq service
  include: deploy_rabbitmq.yml
  when: deploy_rabbitmq | bool

- name: Deploy elasticsearch service
  include: deploy_es.yml
  when: deploy_elasticsearch | bool

- name: Create reportportal service account
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'reportportal-serviceaccount.yaml.j2') | from_yaml }}"

- name: Create reportportal role
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'reportportal-role.yaml.j2') | from_yaml }}"

- name: Create reportportal rolebinding
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'reportportal-rolebinding.yaml.j2') | from_yaml }}"

- name: Create index deployment
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'index-deployment.yaml.j2') | from_yaml }}"

- name: Create index service
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'index-service.yaml.j2') | from_yaml }}"

- name: Create ui deployment
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'ui-deployment.yaml.j2') | from_yaml }}"

- name: Create ui service
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'ui-service.yaml.j2') | from_yaml }}"

- name: Create api deployment
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'api-deployment.yaml.j2') | from_yaml }}"

- name: Create api service
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'api-service.yaml.j2') | from_yaml }}"

- name: Create uat deployment
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'uat-deployment.yaml.j2') | from_yaml }}"

- name: Create uat service
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'uat-service.yaml.j2') | from_yaml }}"

- name: Create analyzer statefulset
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'analyzer-statefulset.yaml.j2') | from_yaml }}"

- name: Create analyzer service
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'analyzer-service.yaml.j2') | from_yaml }}"

- name: Create migration job
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'migration-job.yaml.j2') | from_yaml }}"

- name: Create gateway configmap
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'openshift-gateway-configmap.yaml.j2') | from_yaml }}"

- name: Create gateway deployment
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'openshift-gateway-deployment.yaml.j2') | from_yaml }}"

- name: Create gateway service
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'openshift-gateway-service.yaml.j2') | from_yaml }}"

- name: Create gateway route
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'openshift-gateway-route.yaml.j2') | from_yaml }}"

- name: Create gateway servicemonitor
  community.kubernetes.k8s:
    state: present
    definition: "{{ lookup('template', 'openshift-gateway-servicemonitor.yaml.j2') | from_yaml }}"
