- name: Delete existing elasticsearch snapshot restore job
  community.kubernetes.k8s:
    state: absent
    api_version: batch/v1
    kind: Job
    name: es-s3-snapshot-restore
    namespace: "{{ meta.namespace }}"

- name: Create elasticsearch snapshot restore job
  community.kubernetes.k8s:
    state: present
    force: yes
    definition: "{{ lookup('template', 'es-snapshot-restore-job.yaml.j2') | from_yaml }}"
