- name: Deploy RP app services
  include: deploy_app.yml
  when: deploy_rp | bool

#- name: Remove RP app services
#  include: remove_app.yml
#  when: remove_rp | bool

- name: Create RP service-api servicemonitor
  include: service_api_servicemonitor.yml
  when: enable_rp_service_api_servicemonitor | bool

- name: Fetch ReportPortalRestore Operand
  set_fact:
    rp_restore_cr: "{{ lookup('k8s', kind='ReportPortalRestore', api_version='rp5.reportportal.io/v1', namespace=meta.namespace, resource_name=meta.name) }}"

- name: Recover data for postgresql or elasticsearch
  include: data_recovery.yml
  when:
    - (pg_recovery | bool) or (es_restore | bool)
    - rp_restore_cr.status is undefined or rp_restore_cr.status.conditions[0].type != 'Finished'
