- name: Scale back RP Deployment replicas
  ignore_errors: yes
  k8s_scale:
    api_version: "{{ k8s_item.apiVersion }}"
    kind: Deployment
    namespace: "{{ meta.namespace }}"
    name: "{{ k8s_item.metadata.name }}"
    replicas: "{{ k8s_item.spec.replicas }}"
  register: scale_result
  until: scale_result.result.status == {} or (scale_result.result.status is defined and scale_result.result.status.replicas == k8s_item.spec.replicas)
  retries: 6
  delay: 10
  when:
    - k8s_item.apiVersion is defined
    - k8s_item.metadata.name is defined
    - k8s_item.spec.replicas is defined
  with_items: "{{ rp_deployments }}"
  loop_control:
    loop_var: k8s_item

- operator_sdk.util.k8s_status:
    api_version: rp5.reportportal.io/v1alpha1
    kind: ReportPortalRestore
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    status:
      conditions:
        - LastTransitionTime: '{{ ansible_date_time.iso8601 }}'
          message: 'Postgres WAL recovery finished'
          status: 'False'
          reason: 'Done'
          type: 'Finished'
