# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/rp5.reportportal.io_reportportals.yaml
- bases/rp5.reportportal.io_reportportalrestores.yaml
- bases/rp5.reportportal.io_serviceapiservicemonitors.yaml
# +kubebuilder:scaffold:crdkustomizeresource
