apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportportalrestores.rp5.reportportal.io
spec:
  group: rp5.reportportal.io
  names:
    kind: ReportPortalRestore
    listKind: ReportPortalRestoreList
    plural: reportportalrestores
    singular: reportportalrestore
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: Metadata definition for the ReportPortalRestore object
          type: object
        spec:
          description: Specification of the desired behavior of the ReportPortalRestore Operator.
          properties:
            pg_recovery:
              description: Enable Postgres recovery, need be 'yes' or 'no'
              type: string
            pg_s3_bucket_name:
              description: The s3 Postgres bucket name, need be unique and valid bucket name
              type: string
            pg_restic_snapshot_id:
              description: The restic snapshot id, need be unique and valid restic snapshot id, default to 'latest'
              type: string
            pg_recovery_target_time:
              description: The Postgres recovery target time, need be unique and valid time, e.g. '2020-08-05 08:20:00 UTC'
              type: string
            pg_restic_password:
              description: The s3 Postgres bucket restic password
              type: string
            es_s3_backup_dir:
              description: The Elasticsearch snapshot path dir, if set the snapshot will be enabled
              type: string
            es_snapshot_bucket:
              description: The Elasticsearch snapshot s3 bucket name
              type: string
            es_backup_schedule:
              description: The Elasticsearch snapshot to s3 bucket schedule, crontab schedule format
              type: string
        status:
          description: Status results of an instance of ReportPortalRestore
          properties:
            conditions:
              description: The resulting conditions when a ReportPortalRestore is instantiated
              items:
                properties:
                  status:
                    type: string
                  type:
                    type: string
                  reason:
                    type: string
                  lastTransitionTime:
                    type: string
                type: object
              type: array
          type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
