---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceapiservicemonitors.rp5.reportportal.io
spec:
  group: rp5.reportportal.io
  names:
    kind: ServiceApiServiceMonitor
    listKind: ServiceApiServiceMonitorList
    plural: serviceapiservicemonitors
    singular: serviceapiservicemonitor
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: ServiceApiServiceMonitor is the Schema for the serviceapiservicemonitors API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            name: ReportPortal service-api ServiceMonitor
            type: object
          spec:
            description: Spec defines the desired state of ServiceApiServiceMonitor
            type: object
            properties:
              bearer_token_secret_name:
                description: ReportPortal bearer token secret name
                type: string
              bearer_token_secret_key:
                description: The key in ReportPortal bearer token secret
                type: string
          status:
            description: Status defines the observed state of ServiceApiServiceMonitor
            type: object
            properties:
              conditions:
                description: The resulting conditions when a ServiceApiServiceMonitor is instantiated
                items:
                  properties:
                    status:
                      type: string
                    type:
                      type: string
                    reason:
                      type: string
                    lastTransitionTime:
                      type: string
                  type: object
                type: array
        type: object
    served: true
    storage: true
    subresources:
      status: {}
