# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  crd_csv_verify:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2

    # Runs operator testing with verify
    - name: Run operator testing with verification
      run: docker run -v $PWD/deploy/olm-catalog:/community-operators:z -ti quay.io/operator-framework/operator-testing:latest operator.verify --no-print-directory OP_PATH=community-operators/reportportal-operator VERBOSE=1
